unit UserScript;

uses 'lib\mxpf';

function Initialize: integer;

var
  changed: boolean;
  i, j, k, lastPercent: integer;
  currentFile, currentSignature, editorID, formID, rName, rFormID, rEditorID, rSignature, fIngredient, fEditor, lNewItem, fSignature, fFormID, lEditorID, lSignature, lFormID, cNewItem, cEditorID, cSignature, nItem, nEditorID, nSignature, tIngredient, tEditorID, tSignature, tFormID, povertyFileLoadOrder, dummyDrink, dummyFood, dummyPotion, dummyArrow, dummyAmulet, dummyBoots, dummyCirclet, dummyCuirass, dummyGauntlets, dummyHelmet, dummyRing, dummyShield, dummyBook, dummyIngredient, dummyClutter, dummyResource, dummySeptim, dummySoulGem, dummyBattleaxe, dummyBow, dummyDagger, dummyGreatSword, dummyMace, dummyStaff, dummySword, dummyWarAxe, dummyWarhammer, dummyWeapon1H, dummyWeapon2H: string;
  rec, lvliRecord, rItemRecord, ItemsListubRecord, cItem, lEntries, lEntry, nItems: IInterface;
  referenceKeywords, failedFormIDs, errorFormIDs, cItemsList, cCountsList, lLevelList, lReferenceList, lCountList, blackListLVLI, blackListREFR: TStringList;

begin
	//--------------------------------
	//MXPF Initialization
	//--------------------------------
	InitializeMXPF;
	DefaultOptionsMXPF;

	//Name this whatever you like
	PatchFileByName('Poverty All-in-One Patch.esp');
	
	//Add Poverty as master
	AddMasterIfMissing(mxPatchFile, 'Poverty.esp');
	
	//Set File Header variables
	seev(mxPatchFile, 'CNAM', 'Evrymetul and Elscrux');
	seev(mxPatchFile, 'SNAM', 'All-in-One Patch for Poverty by evrymetul - Automatically generated by xEdit-Patcher by Elscrux');
	
	SetExclusions('Poverty.esp');
	SetInclusions('HearthFires.esm');
	SetInclusions('Dawnguard.esm');
	//SetInclusions('Test.esp');

	//--------------------------------
	//Loading records
	//--------------------------------
	//LoadChildRecords('CELL', 'REFR');
	//LoadChildRecords('WRLD', 'REFR');
	LoadRecords('CONT');
	LoadRecords('FLOR');
	LoadRecords('LVLI');
	LoadRecords('NPC_');
	LoadRecords('TREE');
	
	//--------------------------------
	//MESSAGE: Records loaded
	//--------------------------------
	AddMessage('Records loaded');
	
	//MXPF: Copy to patch
	CopyRecordsToPatch;

	//--------------------------------
	//MESSAGE: Records copied
	//--------------------------------
	AddMessage('Records copied to patch');
	
	//--------------------------------
	//Creating TStringLists
	//--------------------------------
	referenceKeywords := TStringList.Create;
	failedFormIDs := TStringList.Create;
	errorFormIDs := TStringList.Create;
	cItemsList := TStringList.Create;
	cCountsList := TStringList.Create;
	lLevelList := TStringList.Create;
	lReferenceList := TStringList.Create;
	lCountList := TStringList.Create;
	blackListLVLI := TStringList.Create;
	blackListREFR := TStringList.Create;

	//--------------------------------
	//Get dummys from Skyrim & Poverty
	//--------------------------------
	povertyFileLoadOrder := IntToStr(GetLoadOrder(FileByName('Poverty.esp')));
	
	//ALCH
	dummyDrink := povertyFileLoadOrder + '01A21D';
	dummyFood := povertyFileLoadOrder + '01A21E';
	dummyPotion := '6A07E';
	//AMMO
	dummyArrow := '6A0BF';
	//ARMO
	dummyAmulet := povertyFileLoadOrder + '014C9A';
	dummyBoots := '6A0A9';
	dummyCirclet := povertyFileLoadOrder + '019DD5';
	dummyCuirass := '6A0AB';
	dummyGauntlets := '6A0AD';
	dummyHelmet := '6A0AF';
	dummyRing := povertyFileLoadOrder + '014C99';
	dummyShield := '6A0B1';
	//BOOK
	dummyBook := 'D7866';
	//INGR
	dummyIngredient := povertyFileLoadOrder + '01A017';
	//MISC
	dummyClutter := povertyFileLoadOrder + '01A163';
	dummyResource := povertyFileLoadOrder + '01A153';
	dummySeptim := povertyFileLoadOrder + '01A119';
	//SLGM
	dummySoulGem := '6A0C2';
	//WEAP
	dummyBattleaxe := '6A0BB';
	dummyBow := '6A0BD';
	dummyDagger := '20163';
	dummyGreatSword := '6A0B8';
	dummyMace := '6A0BA';
	dummyStaff := povertyFileLoadOrder + '01A116';
	dummySword := '6A0B9';
	dummyWarAxe := '6A0BC';
	dummyWarhammer := '20154';
	dummyWeapon1H := '6B95F';
	dummyWeapon2H := '6B95D';
	
	//--------------------------------
	//MESSAGE: Number of Records
	//--------------------------------
	AddMessage('Patching ' + IntToStr(MaxPatchRecordIndex + 1) + ' Records');
	AddMessage(' ');
	
	//--------------------------------
	//Blacklists LVLI EditorIDs
	//-------------------------------- 
	blackListLVLI.Add('');
	
	//--------------------------------
	//Blacklists REFR EditorIDs
	//--------------------------------
	blackListREFR.Add('DefaultBookShelfBookMarker');
	blackListREFR.Add('AleWhiterunQuest');
	blackListREFR.Add('ArmorBoneCrown');
	blackListREFR.Add('ArmorDragonPriestMaskWoodHelmet');
	blackListREFR.Add('BasketCarry');
	blackListREFR.Add('BYOHHouseGuide');
	blackListREFR.Add('C04HagravenHead');
	blackListREFR.Add('CasSecEntranceCrest');
	blackListREFR.Add('CivilWarMapFlag01');
	blackListREFR.Add('CR12TotemsOfHircine');
	blackListREFR.Add('CW');
	blackListREFR.Add('DA01');
	blackListREFR.Add('DA03RuefulAxe');
	blackListREFR.Add('DA04');
	blackListREFR.Add('DA06Volendrung');
	blackListREFR.Add('DA07');
	blackListREFR.Add('DA08EbonyBlade');
	blackListREFR.Add('DA13Afflicted');
	blackListREFR.Add('DA14');
	blackListREFR.Add('DA16SkullofCorruption');
	blackListREFR.Add('DA16Torpor');
	blackListREFR.Add('DancersFlute');
	blackListREFR.Add('DB003TovaLetter');
	blackListREFR.Add('DB01AventusLetter');
	blackListREFR.Add('DB05ElvenBow');
	blackListREFR.Add('DB06Schedule');
	blackListREFR.Add('DB07Journal');
	blackListREFR.Add('DBArmorGlovesReward');
	blackListREFR.Add('DBBladeOfWoeReward');
	blackListREFR.Add('DBCiceroJournal');
	blackListREFR.Add('DLC01DrawKnife');
	blackListREFR.Add('DLC01DweSchematics');
	blackListREFR.Add('DLC01SoulCairnReaperFragment');
	blackListREFR.Add('DLC01TortureTool01');
	blackListREFR.Add('DLC1BoneHawk');
	blackListREFR.Add('DLC1Book3Valuable');
	blackListREFR.Add('DLC1DarkfallPassageNote');
	blackListREFR.Add('DLC1DawnguardRune');
	blackListREFR.Add('DLC1dunRedwaterDenJournal');
	blackListREFR.Add('DLC1FVBook02English');
	blackListREFR.Add('DLC1IvoryCrown');
	blackListREFR.Add('DLC1LD_Aetheri');
	blackListREFR.Add('DLC1LD_Katria');
	blackListREFR.Add('DLC1nVampireNightPowerNecklaceBats');
	blackListREFR.Add('DLC1RecipeFrenzy1');
	blackListREFR.Add('DLC1RuunvaldJournal');
	blackListREFR.Add('DLC1SoulCairnRJPOI2Note');
	blackListREFR.Add('DLC1SpellTomeConjure');
	blackListREFR.Add('DLC1V');
	blackListREFR.Add('DLC2Bl');
	blackListREFR.Add('DLC2dunFahlbtharzDwarvenHelmet');
	blackListREFR.Add('DLC2dunBloodskalNote01');
	blackListREFR.Add('DLC2dunHaknirScimitar01');
	blackListREFR.Add('DLC2dunK');
	blackListREFR.Add('DLC2dunNchardakCube');
	blackListREFR.Add('DLC2DweKagrumezControlGemInv01');
	blackListREFR.Add('DLC2ExpSpiderExperimentJournal');
	blackListREFR.Add('DLC2FrostmothLetter04');
	blackListREFR.Add('DLC2Hork');
	blackListREFR.Add('DLC2Hrodulf');
	blackListREFR.Add('DLC2IldariJournal');
	blackListREFR.Add('DLC2KagrumezFateBow01');
	blackListREFR.Add('dlc2MerchNote');
	blackListREFR.Add('DLC2POIUshaNote01');
	blackListREFR.Add('DLC2RR');
	blackListREFR.Add('DLC2TG');
	blackListREFR.Add('DLC2TT2HeartStone');
	blackListREFR.Add('dunAbandonedPrisonNote');
	blackListREFR.Add('dunAlftandDwemerStudy01');
	blackListREFR.Add('dunAlftandEndrastsJournal01');
	blackListREFR.Add('dunAlftandJ');
	blackListREFR.Add('dunAlftandManifestJournal01');
	blackListREFR.Add('dunAn');
	blackListREFR.Add('dunB');
	blackListREFR.Add('dunC');
	blackListREFR.Add('dunD');
	blackListREFR.Add('dunEmbershardTatteredJournal');
	blackListREFR.Add('dunF');
	blackListREFR.Add('dunG');
	blackListREFR.Add('dunH');
	blackListREFR.Add('dunIlinaltasDeepAdventurerJournal');
	blackListREFR.Add('dunIronbindLetter');
	blackListREFR.Add('dunK');
	blackListREFR.Add('dunL');
	blackListREFR.Add('dunM');
	blackListREFR.Add('dunN');
	blackListREFR.Add('dunOrotheimJournal');
	blackListREFR.Add('dunP');
	blackListREFR.Add('dunR');
	blackListREFR.Add('dunSaarthalStaffJyrikStaff');
	blackListREFR.Add('dunSerpentsBluffNote');
	blackListREFR.Add('dunShipwreck04TriusNote');
	blackListREFR.Add('dunSilentMoonsLunarBook');
	blackListREFR.Add('dunSteamcragCampNote');
	blackListREFR.Add('dunT');
	blackListREFR.Add('dunU');
	blackListREFR.Add('dunV');
	blackListREFR.Add('dunW');
	blackListREFR.Add('dunYng');
	blackListREFR.Add('EnchArmorDraugrHelmetResistFire03');
	blackListREFR.Add('EnchCircletWaterbreathing');
	blackListREFR.Add('EnchDraugrGreatswordHonedFire03');
	blackListREFR.Add('EnchSteelBattleaxeFierySouls');
	blackListREFR.Add('Favor');
	blackListREFR.Add('FF');
	blackListREFR.Add('FirebrandWine');
	blackListREFR.Add('Freeform');
	blackListREFR.Add('FXdustDropMedWEP');
	blackListREFR.Add('highGateRuinsScroll');
	blackListREFR.Add('ImperialWarHorn');
	blackListREFR.Add('IronSwordBrokenHandle');
	blackListREFR.Add('IronWarAxeBroken');
	blackListREFR.Add('Letter');
	blackListREFR.Add('Markarth');
	blackListREFR.Add('MG03Book');
	blackListREFR.Add('MGRArniel04SoulGem');
	blackListREFR.Add('MGRDestruction');
	blackListREFR.Add('MGRitual02Book');
	blackListREFR.Add('MGRKeening');
	blackListREFR.Add('MQ103FarengarBook');
	blackListREFR.Add('MQ105Note');
	blackListREFR.Add('MQ106DragonParchment');
	blackListREFR.Add('MQPaarthurnaxBook');
	blackListREFR.Add('MS');
	blackListREFR.Add('NN01SinderionsJournal');
	blackListREFR.Add('POI');
	blackListREFR.Add('sc_ArvakSkullUNIQUE');
	blackListREFR.Add('SolitudeToryggWarHorn');
	blackListREFR.Add('SpellTomeTransmuteOreMineral');
	blackListREFR.Add('SovRoastOx');
	blackListREFR.Add('SteelBattleAxeBroken');
	blackListREFR.Add('T0');
	blackListREFR.Add('TG00MadesiRing');
	blackListREFR.Add('TG01HaelgaStatue');
	blackListREFR.Add('TG02BillofSale');
	blackListREFR.Add('TG03SabjornLetter');
	blackListREFR.Add('TG04');
	blackListREFR.Add('TG05GallusJournalPre');
	blackListREFR.Add('TG07');
	blackListREFR.Add('TG08SkeletonKey');
	blackListREFR.Add('TGBook0NightingalesVolume');
	blackListREFR.Add('TGCrown');
	blackListREFR.Add('TGFenceCaravanSatchel');
	blackListREFR.Add('TGLT');
	blackListREFR.Add('TGTQ');
	blackListREFR.Add('TGRFOValueItem');
	blackListREFR.Add('TGRGeneralValueItem');
	blackListREFR.Add('TGTQ03SolitudeLetter');
	blackListREFR.Add('TrapDweBallistaBoltAmmo01');
	blackListREFR.Add('Windhelm');
	blackListREFR.Add('YsgramorsBladePiece07');
	
	lastPercent := 0;

	for i := 0 to MaxPatchRecordIndex do begin
		rec := GetPatchRecord(i);

		//--------------------------------
		//Current process message
		//--------------------------------
		currentFile := BaseName(GetFile(Master(rec)));
		if not (Signature(rec) = currentSignature) then begin
				currentSignature := Signature(rec);
				AddMessage('----------------------------------------------------------------');
				AddMessage('Now patching ' + currentSignature + ' in ' + currentFile);
				AddMessage('----------------------------------------------------------------');
		end;

		//--------------------------------
		//Percent done message
		//--------------------------------
		if not (MaxPatchRecordIndex = 0) then begin
			if ((i  * 100) div MaxPatchRecordIndex) > lastPercent then begin
				AddMessage(IntToStr((i  * 100) div MaxPatchRecordIndex) + '% patched!');
				lastPercent := lastPercent + 1;
			end;
		end;
		
		editorID := geev(rec, 'EDID');
		formID := HexFormID(rec);

		//--------------------------------
		//Process records
		//--------------------------------
		if currentSignature = 'REFR' then begin
			
			//Assign utility variables
			rName := geev(rec, 'NAME');
			rSignature := getSignature(rName);
			rEditorID := getEditorID(rName);
			rFormID := getFormID(rName);
			
			//Check for potential errors and sort out records that shall not be processed
			if Assigned(ebip(rec, 'NAME')) and hasPovertySignature(rSignature) and (not IsInTStringListCopy(blackListREFR, rEditorID)) and (not (Copy(rEditorID, 0, 5) = 'Dummy')) then begin
				
				rItemRecord := RecordByHexFormID(rFormID);
				
				//Add poverty LVLI record
				lvliRecord := AddLVLI(mxPatchFile, rItemRecord, 'REFR', rEditorID, rFormID);
				
				//Add XLIB to reference
				if not Assigned(ebip(rec, 'XLIB')) then
					Add(rec, 'XLIB', true);
				seev(rec, 'XLIB', HexFormID(lvliRecord));
				
				//Check for keywords of the placed base record
				
				
				if IsWinningOverride(rItemRecord) then begin
					for j := 0 to ElementCount(ebip(rItemRecord, 'KWDA')) - 1 do begin
						referenceKeywords.Add(getEditorID(geev(rItemRecord, 'KWDA\[' + IntToStr(j) + ']')));
					end;
				end
				else begin
					for j := 0 to ElementCount(ebip(WinningOverride(rItemRecord), 'KWDA')) - 1 do begin
						referenceKeywords.Add(getEditorID(geev(WinningOverride(rItemRecord), 'KWDA\[' + IntToStr(j) + ']')));
					end;
				end;				
				
				//Change the name
				Case Pos(rSignature, 'ALCH|AMMO|ARMO|BOOK|INGR|MISC|SLGM|WEAP') of
					1: 	begin
							seev(rec, 'NAME', dummyFood);
							if getEditorID(geev(rItemRecord, 'ENIT\Sound - Consume')) = 'ITMPotionUse' then
								seev(rec, 'NAME', dummyDrink);
							for j := 0 to referenceKeywords.Count - 1 do begin
								Case Pos(referenceKeywords[j], 'VendorItemPotion|VendorItemPoison') of
									1: seev(rec, 'NAME', dummyPotion);
									18: seev(rec, 'NAME', dummyPotion);
								end;
							end;
						end;
					6: seev(rec, 'NAME', dummyArrow);
					11: begin
							for j := 0 to referenceKeywords.Count - 1 do begin
								Case Pos(referenceKeywords[j], 'ArmorBoots|ArmorCuirass|ArmorGauntlets|ArmorHelmet|ArmorShield|ClothingCirclet|ClothingRing|ClothingNecklace') of
									1:	begin 
											seev(rec, 'NAME', dummyBoots);
											Break;
										end;
									12: begin 
											seev(rec, 'NAME', dummyCuirass);
											Break;
										end;
									25: begin 
											seev(rec, 'NAME', dummyGauntlets);
											Break;
										end;
									40: begin 
											seev(rec, 'NAME', dummyHelmet);
											Break;
										end;
									52: begin 
											seev(rec, 'NAME', dummyShield);
											Break;
										end;
									64: begin 
											seev(rec, 'NAME', dummyCirclet);
											Break;
										end;
									80: begin 
											seev(rec, 'NAME', dummyRing);
											Break;
										end;
									93: begin 
											seev(rec, 'NAME', dummyAmulet);
											Break;
										end;
								end;
							end;
						end;
					16: seev(rec, 'NAME', dummyBook);
					21: seev(rec, 'NAME', dummyIngredient);
					26: begin
							seev(rec, 'NAME', dummyClutter);
							if rEditorID = 'Gold001' then begin
								seev(rec, 'NAME', dummySeptim);
								Continue;
							end;
							for j := 0 to ReferencedByCount(rItemRecord) - 1 do begin
								if getSignature(geev(ReferencedByIndex(rItemRecord, j), 'Record Header\FormID')) = 'COBJ' then begin
									seev(rec, 'NAME', dummyResource);
									Break;
								end;
							end;
						end;
					31: seev(rec, 'NAME', dummySoulGem);
					36: begin
							for j := 0 to referenceKeywords.Count - 1 do begin
								Case Pos(referenceKeywords[j], 'WeapTypeBattleaxe|WeapTypeBow|WeapTypeDagger|WeapTypeGreatsword|WeapTypeMace|WeapTypeSword|WeapTypeWarAxe|WeapTypeWarhammer|WeapTypeStaff') of
									1: 	begin 
											seev(rec, 'NAME', dummyBattleaxe);
											Break;
										end;
									19: begin 
											seev(rec, 'NAME', dummyBow);
											Break;
										end;
									31: begin 
											seev(rec, 'NAME', dummyDagger);
											Break;
										end;
									46: begin 
											seev(rec, 'NAME', dummyGreatSword);
											Break;
										end;
									65: begin 
											seev(rec, 'NAME', dummyMace);
											Break;
										end;
									78: begin 
											seev(rec, 'NAME', dummySword);
											Break;
										end;
									92: begin 
											seev(rec, 'NAME', dummyWarAxe);
											Break;
										end;
									107:begin 
											seev(rec, 'NAME', dummyWarhammer);
											Break;
										end;
									125:begin 
											seev(rec, 'NAME', dummyStaff);
											Break;
										end;
								end;
							end;
						end;
					else begin
						failedFormIDs.Add(geev(rec, 'Record Header\FormID'));
						Remove(rec);
						Continue;
					end;
				end;
				
				//Remove record if it was not successfully processed
				if not (Copy(getEditorID(geev(rec, 'NAME')), 0, 5) = 'Dummy') then begin
					failedFormIDs.Add(geev(rec, 'Record Header\FormID'));
					Remove(rec);
					Continue;
				end;
				
				//Clear TStringLists
				referenceKeywords.Clear;
			end
			else begin
				Remove(rec);
				Continue;
			end;
		end
		else if currentSignature = 'CONT' then begin
			if Assigned(ebip(rec, 'Items')) then begin
				
				//Add items to list and delete them
				k := 0;
				for j := 0 to ElementCount(ebip(rec, 'Items')) - 1 do begin
					if (not (getSignature(geev(rec, 'Items\[' + IntToStr(k) + ']\CNTO\Item')) = 'LVLI')) and (not (Copy(getEditorID(geev(rec, 'Items\[' + IntToStr(k) + ']\CNTO\Item')), 0, 5) = 'Dummy')) then begin
						cItem := ebip(rec, 'Items\[0]');
						cItemsList.Add(geev(rec, 'Items\[0]\CNTO\Item'));
						cCountsList.Add(geev(rec, 'Items\[0]\CNTO\Count'));
						Remove(cItem);
					end
					else begin
						k := k + 1;
					end;
				end;

				if cItemsList.Count = 0 then begin
					Remove(rec);
					Continue;
				end;
				
				//Create new items and their Leveled List
				for j := 0 to cItemsList.Count - 1 do begin
					cNewItem := cItemsList[j];
					if ContainsText(cNewItem, 'Error: Could not be resolved') then begin
						errorFormIDs.Add(cNewItem + ' in ' + editorID ' in file ' + currentFile);
						Continue;
					end;
					cEditorID := getEditorID(cNewItem);
					//Add poverty LVLI record
					lvliRecord := AddLVLI(mxPatchFile, rec, 'CONT', cEditorID, getFormID(cNewItem));
					//Add new item and change its values
					cItem := ElementAssign(ebip(rec, 'Items'), HighInteger, nil, false);
					seev(cItem, 'CNTO\Item', geev(lvliRecord, 'Record Header\FormID'));
					seev(cItem, 'CNTO\Count', cCountsList[j]);
				end;
			end
			else begin
				Remove(rec);
				Continue;
			end;
			cItemsList.Clear;
			cCountsList.Clear;
		end
		else if currentSignature = 'FLOR' then begin
			if Assigned(ebip(rec, 'PFIG')) then begin
			
				//Assign utility variables
				fIngredient := geev(rec, 'PFIG');
				fSignature := getSignature(fIngredient);
				fEditor := getEditorID(fIngredient);
				fFormID := getFormID(fIngredient);
				
				//Sort out records that shall not be processed
				if (not (fSignature = 'ALCH')) and (not (fSignature = 'INGR')) then begin
					Remove(rec);
					Continue;
				end;
				
				//Add poverty LVLI record
				lvliRecord := AddLVLI(mxPatchFile, rec, 'FLOR', fEditor, fFormID);
				
				//Change PFIG value
				seev(rec, 'PFIG', geev(lvliRecord, 'Record Header\FormID'));
			end
			else begin
				Remove(rec);
				Continue;
			end;
		end
		else if currentSignature = 'LVLI' then begin
			lEntries := ebip(rec, 'Leveled List Entries');
			if Assigned(lEntries) and (not (IsInTStringListCopy(blackListLVLI, editorID))) then begin

				//Add items to list and delete them
				k := 0;
				for j := 0 to ElementCount(lEntries) - 1 do begin
					if (not (getSignature(geev(rec, 'Leveled List Entries\[' + IntToStr(k) + ']\LVLO\Reference')) = 'LVLI')) and (not (Copy(getEditorID(geev(rec, 'Leveled List Entries\[' + IntToStr(k) + ']\LVLO\Reference')), 0, 5) = 'Dummy')) then begin
						lEntry := ebip(rec, 'Leveled List Entries\[' + IntToStr(k) + ']');
						lLevelList.Add(geev(rec, 'Leveled List Entries\[' + IntToStr(k) + ']\LVLO\Level'));
						lReferenceList.Add(geev(rec, 'Leveled List Entries\[' + IntToStr(k) + ']\LVLO\Reference'));
						lCountList.Add(geev(rec, 'Leveled List Entries\[' + IntToStr(k) + ']\LVLO\Count'));
						Remove(lEntry);
					end
					else begin
						k := k + 1;
					end;
				end;
				
				if lLevelList.Count = 0 then begin
					Remove(rec);
					Continue;
				end;
				
				//Create new items and their Leveled List
				for j := 0 to lReferenceList.Count - 1 do begin
					lNewItem := lReferenceList[j];
					
					//Check for errors
					if ContainsText(lNewItem, 'Error: Could not be resolved') then begin
						errorFormIDs.Add(lNewItem + ' in ' + editorID);
						Continue;
					end;
					
					//Assign utility variables
					lEditorID := getEditorID(lNewItem);
					lSignature := getSignature(lNewItem);
					
					//Add poverty LVLI record
					lvliRecord := AddLVLI(mxPatchFile, rec, 'LVLI', lEditorID, getFormID(lNewItem));
					
					//Add new entry and change its values
					lEntry := ElementAssign(lEntries, HighInteger, nil, false);
					seev(lEntry, 'LVLO\Level', lLevelList[j]);
					seev(lEntry, 'LVLO\Reference', geev(lvliRecord, 'Record Header\FormID'));
					seev(lEntry, 'LVLO\Count', lCountList[j]);
				end;
			end
			else begin
				Remove(rec);
				Continue;
			end;
			lLevelList.Clear;
			lReferenceList.Clear;
			lCountList.Clear;
		end
		else if currentSignature = 'NPC_' then begin
			if Assigned(ebip(rec, 'Items')) then begin
				//Add items to list and delete them
				k := 0;
				for j := 0 to ElementCount(ebip(rec, 'Items')) - 1 do begin
					nSignature := getSignature(geev(rec, 'Items\[' + IntToStr(k) + ']\CNTO\Item'));
					if (not (nSignature = 'LVLI')) and (not (nSignature = 'KEYM')) and (not (nSignature = 'WEAP')) and (not (Copy(getEditorID(nSignature), 0, 5) = 'Dummy')) then begin
						cItem := ebip(rec, 'Items\[0]');
						cItemsList.Add(geev(rec, 'Items\[0]\CNTO\Item'));
						cCountsList.Add(geev(rec, 'Items\[0]\CNTO\Count'));
						Remove(cItem);
					end
					else begin
						k := k + 1;
					end;
				end;
				
				if cItemsList.Count = 0 then begin
					Remove(rec);
					Continue;
				end;
				
				for j := 0 to cItemsList.Count - 1 do begin
					cNewItem := cItemsList[j];
					
					//Check for errors
					if ContainsText(cNewItem, 'Error: Could not be resolved') then begin
						errorFormIDs.Add(cNewItem + ' in ' + editorID);
						Continue;
					end;
					
					//Assign utility variables
					cEditorID := getEditorID(cNewItem);
					nSignature := getSignature(cNewItem);
					
					//Add poverty LVLI record
					lvliRecord := AddLVLI(mxPatchFile, rec, 'NPC_', cEditorID, getFormID(cNewItem));
					
					//Add new item and change its values
					cItem := ElementAssign(ebip(rec, 'Items'), HighInteger, nil, false);
					seev(cItem, 'CNTO\Item', geev(lvliRecord, 'Record Header\FormID'));
					seev(cItem, 'CNTO\Count', cCountsList[j]);
				end;
			end
			else begin
				Remove(rec);
				Continue;
			end;
			cItemsList.Clear;
			cCountsList.Clear;
		end
		else if currentSignature = 'TREE' then begin
			if Assigned(ebip(rec, 'PFIG')) then begin
				tIngredient := geev(rec, 'PFIG');
				tEditorID := getEditorID(tIngredient);
				tSignature := getSignature(tIngredient);
				tFormID := getFormID(tIngredient);
				if not (tSignature = 'ALCH') then begin
					if not (tSignature = 'INGR') then begin
						Remove(rec);
						Continue;
					end;
				end;
				
				//Add poverty LVLI record
				lvliRecord := AddLVLI(mxPatchFile, rec, 'TREE', tEditorID, tFormID);
				
				//Change PFIG value
				seev(rec, 'PFIG', geev(lvliRecord, 'Record Header\FormID'));
			end
			else begin
				Remove(rec);
				Continue;
			end;
		end;
	end;

	//--------------------------------
	//Final warnings
	//--------------------------------
	if failedFormIDs.Count > 0 then begin
		AddMessage(' ');
		AddMessage('WARNING: Those References were not patched due to a lack of keywords in their base record');
		AddMessage(' ');
		AddMessageTStringList(failedFormIDs);
    end;
	if errorFormIDs.Count > 0 then begin
		AddMessage(' ');
		AddMessage('WARNING: Those records could not be used as they contain an error | Please contact the mod author politely');
		AddMessage(' ');
		AddMessageTStringList(errorFormIDs);
    end;

	//--------------------------------
	//MXPF Finalization
	//--------------------------------
	FinalizeMXPF;
end;

//--------------------------------
//Utility functions
//--------------------------------

function getFormID(s: string): string;
begin
  Result := Copy(s, Pos('[', s) + 6, 8);
end;

function getEditorID(s: string): string;
begin
  Result := Copy(s, 0, Pos(' ', s) - 1);
end;

function getSignature(s: string): string;
begin
  Result := Copy(s, Pos('[', s) + 1, 4);
end;

function RecordByEditorIDAllFiles(group, eid: string): IInterface;
var
    i: integer;
begin
    Result := nil;
    for i := 0 to FileCount - 1 do begin
				if HasGroup(FileByIndex(i), group) then begin
          if Assigned(MainRecordByEditorID(GroupBySignature(FileByIndex(i), group), eid)) then begin
						Result := MainRecordByEditorID(GroupBySignature(FileByIndex(i), group), eid);
            Exit;
          end
				end
    end
end;

function IsInTStringList(sl: TStringList; s: string): boolean;
var
	i: integer;
begin
	Result := false;
	for i := 0 to sl.Count - 1 do begin
		if sl.IndexOf(s) > -1  then begin
			Result := true;
			Exit;
		end;
	end;
end;

function IsInTStringListCopy(sl: TStringList; s: string): boolean;
var
	i: integer;
begin
	Result := false;
	for i := 0 to sl.Count - 1 do begin
		if Copy(sl[i], 0, Length(s)) = s then begin
			Result := true;
			Exit;
		end;
	end;
end;

procedure AddMessageTStringList(sl: TStringList);
var
	i: integer;
begin
	for i := 0 to sl.Count - 1 do begin
		AddMessage(sl[i]);
	end;
end;

procedure AddMessageCurrentItemsStructure(rec: IInterface);
var
	i: integer;
begin
	for i := 0 to ElementCount(ebip(rec, 'Items')) - 1 do begin
		AddMessage(IntToStr(i) + ': ' + geev(rec, 'Items\[' + IntToStr(i) + ']\CNTO\Item'));
	end;
end;

function hasPovertySignature(s: string): bool;
var
	i: integer;
begin
	Result := false;
	if ContainsText('ALCH|AMMO|ARMO|BOOK|INGR|MISC|SLGM|WEAP', s) then
		Result := true;
end;

function AddLVLI(f, rec: IInterface; origin, eid, fid: string): IInterface;
var
	i: integer;
	referenceKeywords: TStringList;
	signature, reference, povertyFileLoadOrder, pAmmo, pArmor, pBook, pIngredient, pClutter, pSoulGem, pWeapon, pFood, pHarvestFoodFlora, pPotion, pResource, pGold, pDrink, pHarvestIngredientsFlora, pHarvestFoodNPC, pHarvestResourceNPC, pAmmoNPC, pMerchantGold, pBookSpell, pHarvestFoodFloraHanging, pHarvestIngredientsNPC, pMineNotInUse, pBugFishNotInUse: string;
	innerlvli, lvli, itemRecord, fidRecord: IInterface;
begin
	//Get global value from Poverty
	povertyFileLoadOrder := IntToStr(GetLoadOrder(FileByName('Poverty.esp')));
	//ALCH
	pHarvestFoodFlora := povertyFileLoadOrder + '00AA19';
	pHarvestFoodNPC := povertyFileLoadOrder + '01A023';
	pFood := povertyFileLoadOrder + '00AA18';
	pPotion := povertyFileLoadOrder + '00AA1A';
	pDrink := povertyFileLoadOrder + '014C21';
	//AMMO
	pAmmo := povertyFileLoadOrder + '000802';
	pAmmoNPC := povertyFileLoadOrder + '01A17E';
	//ARMO
	pArmor := povertyFileLoadOrder + '005911';
	//BOOK
	pBook := povertyFileLoadOrder + '005912';
	pBookSpell := povertyFileLoadOrder + '01A21F';
	//INGR
	pIngredient := povertyFileLoadOrder + '005913';
	pHarvestIngredientsNPC := povertyFileLoadOrder + '01A3DA';
	pHarvestIngredientsFlora := povertyFileLoadOrder + '014CA1';
	//MISC
	pClutter := povertyFileLoadOrder + '005914';
	pResource := povertyFileLoadOrder + '00AA1B';
	pHarvestResourceNPC := povertyFileLoadOrder + '01A162';
	pGold := povertyFileLoadOrder + '00FB1E';
	pMerchantGold := povertyFileLoadOrder + '01A17F';
	//SLGM
	pSoulGem := povertyFileLoadOrder + '005915';
	//WEAP
	pWeapon := povertyFileLoadOrder + '005916';
	//Not used right now
	pHarvestFoodFloraHanging := povertyFileLoadOrder + '01A3D7';
	pMineNotInUse := povertyFileLoadOrder + '01A44E';
	pBugFishNotInUse := povertyFileLoadOrder + '01A44F';
	
	referenceKeywords := TStringList.Create;
	
	//If reference is LVLI get the first non LVLI entry
	fidRecord := RecordByHexFormID(fid);
	if not IsWinningOverride(fidRecord) then
		fidRecord := WinningOverride(fidRecord);
	signature := getSignature(BaseName(fidRecord));
	
	if signature = 'LVLI' then begin
		innerlvli := RecordByHexFormID(getFormID(geev(fidRecord, 'Leveled List Entries\[0]\LVLO\Reference')));
		while Assigned(innerlvli) and (signature = 'LVLI') do begin
			signature := getSignature(BaseName(innerlvli));
			if signature = 'LVLI' then begin
				if Assigned(RecordByHexFormID(getFormID(geev(innerlvli, 'Leveled List Entries\[0]\LVLO\Reference')))) then begin
					innerlvli := WinningOverride(RecordByHexFormID(getFormID(geev(innerlvli, 'Leveled List Entries\[0]\LVLO\Reference'))));
					if not IsWinningOverride(innerlvli) then
						innerlvli := WinningOverride(innerlvli);
				end
				else begin
					signature := getSignature(BaseName(fidRecord));
				end;
			end;
		end;
	end
	else begin
		innerlvli := fidRecord;
	end;
	
	//Special cases
	if ContainsText(geev(fidRecord, 'EDID'), 'Gold') and ContainsText(geev(fidRecord, 'EDID'), 'Vendor') then begin
		eid := eid + '_MERCHANT';
	end
	else if ContainsText(geev(fidRecord, 'EDID'), 'SpellTome') or ContainsText(geev(fidRecord, 'EDID'), 'Scroll') then begin
		eid := eid + '_SPELL';
	end
	else if origin = 'NPC_' then begin
		for i := 0 to ReferencedByCount(fidRecord) - 1 do begin
			if getSignature(geev(ReferencedByIndex(fidRecord, i), 'Record Header\FormID')) = 'COBJ' then begin
				eid := eid + '_NPC';
				Break;
			end;
		end;
		if signature = 'AMMO' then
			eid := eid + '_NPC';
	end;
	
	//Add LVLI record
	lvli := RecordByEditorIDAllFiles('LVLI', 'p' + eid);
	if not Assigned(lvli) then begin
		
		//Add group record and lvliRecord
		if not Assigned(GroupBySignature(f, 'LVLI')) then
			Add(f, 'LVLI', true);
		lvli := Add(GroupBySignature(f, 'LVLI'), 'LVLI', true);
		Result := lvli;
		//Add EditorID
		Add(lvli, 'EDID', true);
		seev(lvli, 'EDID', 'p' + eid);
		
		//Add Flag
		SetNativeValue(ebip(lvli, 'LVLF'), GetNativeValue(ebip(lvli, 'LVLF')) or 1 shl 1);
		
		//Add Count
		Add(lvli, 'LLCT', true);
		seev(lvli, 'LLCT', '1');
		
		//Add Leveled List Entry
		Add(lvli, 'Leveled List Entries', true);
		seev(lvli, 'Leveled List Entries\[0]\LVLO\Level', '1');
		seev(lvli, 'Leveled List Entries\[0]\LVLO\Reference', fid);
		seev(lvli, 'Leveled List Entries\[0]\LVLO\Count', '1');
		//Add Global
		Add(lvli, 'LVLG', true);
		if IsWinningOverride(fidRecord) then begin
			for i := 0 to ElementCount(ebip(fidRecord, 'KWDA')) - 1 do begin
				referenceKeywords.Add(getEditorID(geev(fidRecord, 'KWDA\[' + IntToStr(i) + ']')));
			end;
		end
		else begin
			for i := 0 to ElementCount(ebip(WinningOverride(fidRecord), 'KWDA')) - 1 do begin
				referenceKeywords.Add(getEditorID(geev(WinningOverride(fidRecord), 'KWDA\[' + IntToStr(i) + ']')));
			end;
		end;
		Case Pos(signature, 'ALCH|AMMO|ARMO|BOOK|INGR|MISC|SLGM|WEAP|SCRL') of
			//Process ALCH global
			1: 	begin
					if (origin = 'FLOR') or (origin = 'TREE') then begin
						seev(lvli, 'LVLG', pHarvestFoodFlora);
					end
					else if (origin = 'NPC_') then begin
						seev(lvli, 'LVLG', pHarvestFoodNPC);
					end
					else begin
						seev(lvli, 'LVLG', pFood);
						if getEditorID(geev(fidRecord, 'ENIT\Sound - Consume')) = 'ITMPotionUse' then
							seev(lvli, 'LVLG', pDrink);
						for i := 0 to referenceKeywords.Count - 1 do begin
							Case Pos(referenceKeywords[i], 'VendorItemPotion|VendorItemPoison') of
								1: seev(lvli, 'LVLG', pPotion);
								18: seev(lvli, 'LVLG', pPotion);
							end;
						end;
					end;
				end;
			//Process AMMO global
			6: 	begin
					if Copy(eid, length(eid) - 3, 4) = '_NPC' then begin
						seev(lvli, 'LVLG', pAmmoNPC);
					end
					else begin
						seev(lvli, 'LVLG', pAmmo);
					end;
				end;
			//Process ARMO global
			11: seev(lvli, 'LVLG', pArmor);
			//Process BOOK global
			16: begin
					if Copy(eid, length(eid) - 5, 6) = '_SPELL' then begin
						seev(lvli, 'LVLG', pBookSpell);
					end
					else begin
						seev(lvli, 'LVLG', pBook);
					end;
				end;
			//Process INGR global
			21: begin
					if (origin = 'FLOR') or (origin = 'TREE') then begin
						seev(lvli, 'LVLG', pHarvestIngredientsFlora);
					end
					else if origin = 'NPC_' then begin
						seev(lvli, 'LVLG', pHarvestIngredientsNPC);
					end
					else begin
						seev(lvli, 'LVLG', pIngredient);
					end;
				end;
			//Process MISC global
			26: begin
					seev(lvli, 'LVLG', pClutter);
					if Copy(eid, length(eid) - 8, 9) = '_MERCHANT' then begin
						seev(lvli, 'LVLG', pMerchantGold);
					end
					else if ContainsText(geev(fidRecord, 'EDID'), 'Gold') then begin
						seev(lvli, 'LVLG', pGold);
					end;
					if Copy(eid, length(eid) - 3, 4) = '_NPC' then begin
						seev(lvli, 'LVLG', pHarvestResourceNPC);
					end
					else begin
						for i := 0 to ReferencedByCount(innerlvli) - 1 do begin
							if getSignature(geev(ReferencedByIndex(innerlvli, i), 'Record Header\FormID')) = 'COBJ' then begin
								seev(lvli, 'LVLG', pResource);
								Break;
							end;
						end;
					end;
				end;
			//Process SLGM global
			31: seev(lvli, 'LVLG', pSoulGem);
			//Process WEAP global
			36: seev(lvli, 'LVLG', pWeapon);
			//Process SCRL global
			41: seev(lvli, 'LVLG', pBookSpell);
		end;
	end
	else begin
		Result := lvli;
	end;
end;

end.
