unit UserScript;

uses 'lib\mxpf';

function Initialize: integer;

var
  changed: boolean;
  i, j, k, lastPercent: integer;
  currentFile, currentSignature, editorID, formID, rName, rFormID, rEditorID, rSignature, item, fIngredient, fEditor, lNewItem, fSignature, fFormID, lEditorID, lSignature, lFormID, cNewItem, cEditorID, cSignature, nItem, nEditorID, nSignature, tIngredient, tEditorID, tSignature, tFormID, povertyFileLoadOrder, dummyDrink, dummyFood, dummyPotion, dummyArrow, dummyAmulet, dummyBoots, dummyCirclet, dummyCuirass, dummyGauntlets, dummyHelmet, dummyRing, dummyShield, dummyBook, dummyIngredient, dummyClutter, dummyResource, dummySeptim, dummySoulGem, dummyBattleaxe, dummyBow, dummyDagger, dummyGreatSword, dummyMace, dummyStaff, dummySword, dummyWarAxe, dummyWarhammer, dummyWeapon1H, dummyWeapon2H: string;
  rec, lvliRecord, rItemRecord, ItemsListubRecord, cItem, lEntries, lEntry, nItems: IInterface;
  referenceKeywords, failedFormIDs, errorFormIDs, cItemsList, cCountsList, lLevelList, lReferenceList, lCountList, blackList: TStringList;

begin
	//--------------------------------
	//MXPF Initialization
	//--------------------------------
	InitializeMXPF;
	DefaultOptionsMXPF;

	//Name this whatever you like
	PatchFileByName('Poverty All-in-One Patch.esp');
	
	//Add USSEP and Poverty as master
	AddMasterIfMissing(mxPatchFile, 'Unofficial Skyrim Special Edition Patch.esp');
	AddMasterIfMissing(mxPatchFile, 'Poverty.esp');
	
	//Set File Header variables
	seev(mxPatchFile, 'CNAM', 'Evrymetul and Elscrux');
	seev(mxPatchFile, 'SNAM', 'All-in-One Patch for Poverty by evrymetul - Automatically generated by xEdit-Patcher by Elscrux');
	
	SetExclusions('Poverty.esp');
	SetInclusions('HearthFires.esm');
	SetInclusions('Dawnguard.esm');

	//--------------------------------
	//Loading records
	//--------------------------------
	LoadChildRecords('CELL', 'REFR');
	LoadChildRecords('WRLD', 'REFR');
	LoadRecords('CONT');
	LoadRecords('FLOR');
	LoadRecords('LVLI');
	LoadRecords('NPC_');
	LoadRecords('TREE');
	
	
	//--------------------------------
	//MESSAGE: Records loaded
	//--------------------------------
	AddMessage('Records loaded');
	
	//MXPF: Copy to patch
	CopyRecordsToPatch;
	
	
	//--------------------------------
	//MESSAGE: Records copied
	//--------------------------------
	AddMessage('Records copied to patch');
	
	
	//--------------------------------
	//Creating TStringLists
	//--------------------------------
	referenceKeywords := TStringList.Create;
	failedFormIDs := TStringList.Create;
	errorFormIDs := TStringList.Create;
	cItemsList := TStringList.Create;
	cCountsList := TStringList.Create;
	lLevelList := TStringList.Create;
	lReferenceList := TStringList.Create;
	lCountList := TStringList.Create;
	blackList := TStringList.Create;
	
	
	//--------------------------------
	//Get dummys from Skyrim & Poverty
	//--------------------------------
	povertyFileLoadOrder := IntToStr(GetLoadOrder(FileByName('Poverty.esp')));
	
	//ALCH
	dummyDrink := povertyFileLoadOrder + '01A21D';
	dummyFood := povertyFileLoadOrder + '01A21E';
	dummyPotion := '6A07E';
	//AMMO
	dummyArrow := '6A0BF';
	//ARMO
	dummyAmulet := povertyFileLoadOrder + '014C9A';
	dummyBoots := '6A0A9';
	dummyCirclet := povertyFileLoadOrder + '019DD5';
	dummyCuirass := '6A0AB';
	dummyGauntlets := '6A0AD';
	dummyHelmet := '6A0AF';
	dummyRing := povertyFileLoadOrder + '014C99';
	dummyShield := '6A0B1';
	//BOOK
	dummyBook := 'D7866';
	//INGR
	dummyIngredient := povertyFileLoadOrder + '01A017';
	//MISC
	dummyClutter := povertyFileLoadOrder + '01A163';
	dummyResource := povertyFileLoadOrder + '01A153';
	dummySeptim := povertyFileLoadOrder + '01A119';
	//SLGM
	dummySoulGem := '6A0C2';
	//WEAP
	dummyBattleaxe := '6A0BB';
	dummyBow := '6A0BD';
	dummyDagger := '20163';
	dummyGreatSword := '6A0B8';
	dummyMace := '6A0BA';
	dummyStaff := povertyFileLoadOrder + '01A116';
	dummySword := '6A0B9';
	dummyWarAxe := '6A0BC';
	dummyWarhammer := '20154';
	dummyWeapon1H := '6B95F';
	dummyWeapon2H := '6B95D';
	
	
	//--------------------------------
	//MESSAGE: Number of Records
	//--------------------------------
	AddMessage('Patching ' + IntToStr(MaxPatchRecordIndex + 1) + ' Records');
	AddMessage(' ');
	
	
	//--------------------------------
	//Blacklist CONT EditorIDs
	//--------------------------------
	
	blackList.Add('DEMO');
	blackList.Add('DLC01QA');
	blackList.Add('DLC02QA');
	blackList.Add('DLC2dunFrostmoonVendorChest');
	blackList.Add('DLC2MaximianPack');
	blackList.Add('e3DEMO');
	blackList.Add('E3Demo');
	blackList.Add('MQ101BarracksChest02');
	blackList.Add('MQ201ElenwenOfficeChest');
	blackList.Add('QA');
	blackList.Add('SkyHavenArmoryChest');
	
	
	//--------------------------------
	//Blacklist LVLI EditorIDs
	//--------------------------------
	
	blackList.Add('ArmorCompanionsSet');
	blackList.Add('ArmorElvenSet');
	blackList.Add('ArmorGlassSet');
	blackList.Add('ArmorHideSet');
	blackList.Add('ArmorImperialHeavyHelmets');
	blackList.Add('ArmorImperialHeavySet');
	blackList.Add('ArmorImperialLightSet');
	blackList.Add('ArmorImperialStuddedSet');
	blackList.Add('ArmorIronSet');
	blackList.Add('ArmorLeatherSet');
	blackList.Add('ArmorOrcSet');
	blackList.Add('ArmorReachHelmet');
	blackList.Add('ArmorScaledSet');
	blackList.Add('ArmorStormcloakBearSet');
	blackList.Add('ArmorStormcloakHelmets');
	blackList.Add('ArmorStormcloakSet');
	blackList.Add('ArmorStuddedSet');
	blackList.Add('BYOHHouseTestItems');
	blackList.Add('BYOHLItemInnRuralDrinkNewWines');
	blackList.Add('BYOHRelationshipAdoptionLItemChildrensClothes');
	blackList.Add('ClothesFarm');
	blackList.Add('CW01BPlayerHelpItems');
	blackList.Add('CWBearArmorPlayerReward');
	blackList.Add('CWCourierDocuments');
	blackList.Add('CWFinaleFactionLeaderSwordList');
	blackList.Add('CWPlayerUniform');
	blackList.Add('CWRankReward');
	blackList.Add('CWSoldierImperialGear');
	blackList.Add('CWSoldierSonsGear');
	blackList.Add('CWSoldierWoundedOutfit');
	blackList.Add('DA03AxeDeathItem');
	blackList.Add('DA09DawnbreakerList');
	blackList.Add('DA14RingDeathItem');
	blackList.Add('DA14StaffDeathItem');
	blackList.Add('DB02ShackKey');
	blackList.Add('DB08DeathBook');
	blackList.Add('DeathContainerList');
	blackList.Add('DeathItemDwarvenSphere');
	blackList.Add('DLC1DawnGuardHelmet75');
	blackList.Add('DLC1FalmerShamanWeapon');
	blackList.Add('DLC1LItemDaedric');
	blackList.Add('DLC1LItemDawnguard');
	blackList.Add('DLC1LItemDisguisedHunterInventory');
	blackList.Add('DLC1LItemFalmer');
	blackList.Add('DLC1LItemGargoyleMineralsRaw100');
	blackList.Add('DLC1LItemKeeper');
	blackList.Add('DLC1LitemStaffFalmer');
	blackList.Add('DLC1LItemStaffFalmer');
	blackList.Add('DLC1LItemVampireCuirass');
	blackList.Add('DLC1LItemWeaponDawnguardCrossbowLoot75Gated');
	blackList.Add('DLC1LItemWeaponFalmerShaman');
	blackList.Add('DLC1RV03HunterArmor');
	blackList.Add('DLC1RV05RemainsList');
	blackList.Add('DLC1SublistEnchCrossbow');
	blackList.Add('DLC1SublistEnchDwarvenCrossbow');
	blackList.Add('DLC1SublistEnchVampireRobes');
	blackList.Add('DLC1SublistKeeper');
	blackList.Add('DLC1SublistStaffDestructionFalmer');
	blackList.Add('DLC1WrathmanSummonedWeapon2H');
	blackList.Add('DLC2BlacksmithArmorExtra100');
	blackList.Add('DLC2BlankStaff');
	blackList.Add('DLC2Bonemold');
	blackList.Add('DLC2Chitin');
	blackList.Add('DLC2dunHaknirGhostLeveledList');
	blackList.Add('DLC2dunKolbjornLItemMinerClothes');
	blackList.Add('DLC2ExpSpiderAlbinoDeathItemButt');
	blackList.Add('DLC2LItemArmorBootsHeavy');
	blackList.Add('DLC2LItemArmorBootsLight');
	blackList.Add('DLC2LitemArmorBootsLight');
	blackList.Add('DLC2LItemArmorCuirassHeavy');
	blackList.Add('DLC2LItemArmorCuirassLight');
	blackList.Add('DLC2LItemArmorGauntletsHeavy');
	blackList.Add('DLC2LItemArmorGauntletsLight');
	blackList.Add('DLC2LItemArmorHelmetHeavy');
	blackList.Add('DLC2LItemArmorHelmetLight');
	blackList.Add('DLC2LItemArmorShieldHeavy');
	blackList.Add('DLC2LitemArmorShieldHeavy');
	blackList.Add('DLC2LItemArmorShieldLight');
	blackList.Add('DLC2LItemBook');
	blackList.Add('DLC2LItemDraugrHulkingShield67');
	blackList.Add('DLC2LItemDrink75');
	blackList.Add('DLC2LItemIldariRobesDestruction');
	blackList.Add('DLC2LItemIngredientFoodPrepared');
	blackList.Add('DLC2LItemIngredientsCommon');
	blackList.Add('DLC2LItemIngredientsRare');
	blackList.Add('DLC2LItemIngredientsUncommon');
	blackList.Add('DLC2LItemSpellTomes');
	blackList.Add('DLC2LItemSpellTOmes');
	blackList.Add('DLC2LitemSpellTomes');
	blackList.Add('DLC2LItemWeaponBattleAxe');
	blackList.Add('DLC2LItemWeaponBow');
	blackList.Add('DLC2LItemWeaponDagger');
	blackList.Add('DLC2LItemWeaponGreatSword');
	blackList.Add('DLC2LItemWeaponMace');
	blackList.Add('DLC2LItemWeaponSword');
	blackList.Add('DLC2LItemWeaponWarAxe');
	blackList.Add('DLC2LItemWeaponWarhammer');
	blackList.Add('DLC2LootRieklingSpears50');
	blackList.Add('DLC2MerilarRendasDeathItem');
	blackList.Add('DLC2MQ06Miraak');
	blackList.Add('DLC2NordicHeavyBoss');
	blackList.Add('DLC2NordicShield20');
	blackList.Add('DLC2OutfitSkaalHatChance50');
	blackList.Add('DLC2SpellBook');
	blackList.Add('DLC2Stalhrim');
	blackList.Add('DLC2SublistEnchArmor');
	blackList.Add('DLC2SublistEnchNordic');
	blackList.Add('DLC2SublistEnchStahlrim');
	blackList.Add('DLC2SublistEnchStalhrim');
	blackList.Add('dunHillgrundsTombRewardList');
	blackList.Add('dunLItemFolgunthurMikrulSword');
	blackList.Add('dunLItemFrostmereBlade');
	blackList.Add('dunLItemGeirmundSigdisBow');
	blackList.Add('dunMarkarthWizardMeleeSecurity');
	blackList.Add('dunSilentMoonsLItemEnch');
	blackList.Add('GuardGear');
	blackList.Add('LItemApothecaryRecipesCommon100');
	blackList.Add('LItemArmorBootsHeavy');
	blackList.Add('LItemArmorBootsLight');
	blackList.Add('LitemArmorBootsLight');
	blackList.Add('LItemArmorCuirassHeavy');
	blackList.Add('LItemArmorCuirassLight');
	blackList.Add('LItemArmorDwarven');
	blackList.Add('LItemArmorGauntletsHeavy');
	blackList.Add('LItemArmorGauntletsLight');
	blackList.Add('LItemArmorHelmetHeavy');
	blackList.Add('LItemArmorHelmetLight');
	blackList.Add('LItemArmorShieldHeavy');
	blackList.Add('LitemArmorShieldHeavy');
	blackList.Add('LItemArmorShieldLight');
	blackList.Add('LItemBandit');
	blackList.Add('LItemBlacksmithMinDagger');
	blackList.Add('LItemBook');
	blackList.Add('LItemClothesFarm');
	blackList.Add('LItemClothesRegular');
	blackList.Add('LItemClothesWork');
	blackList.Add('LItemDA13Armor');
	blackList.Add('LItemDawnguard');
	blackList.Add('LItemDragonPriestStaff100');
	blackList.Add('LItemDraugr');
	blackList.Add('LItemDwarvenOnly');
	blackList.Add('LItemEnchCirclet');
	blackList.Add('LItemEnchDaedricAny');
	blackList.Add('LItemEnchImperialSword');
	blackList.Add('LItemEnchNecklace');
	blackList.Add('LItemEnchNecromancerRobes');
	blackList.Add('LItemEnchOrcishBattleaxe');
	blackList.Add('LItemEnchRing');
	blackList.Add('LItemFalmerWeapon');
	blackList.Add('LItemFoodBlackBriarMead100');
	blackList.Add('LItemFoodChild');
	blackList.Add('LItemFoodHonningbrewMead100');
	blackList.Add('LItemFoodRaw');
	blackList.Add('LItemForsworn');
	blackList.Add('LItemGemEmpty');
	blackList.Add('LItemGems');
	blackList.Add('LItemGutterSaint');
	blackList.Add('LItemHunterWeaponBow');
	blackList.Add('LItemIngotGold50');
	blackList.Add('LItemIngredientFoodPrepared');
	blackList.Add('LItemIngredientsCommon');
	blackList.Add('LItemIngredientsRare');
	blackList.Add('LItemIngredientsUncommon');
	blackList.Add('LItemIngredientUncommonSame75');
	blackList.Add('LItemIngredientsUnderground');
	blackList.Add('LItemIronOrSteel');
	blackList.Add('LItemJewelryCirclet');
	blackList.Add('LItemJewelryNecklace');
	blackList.Add('LItemJewelryRing');
	blackList.Add('LItemJewelryRingSmall');
	blackList.Add('LitemJunk');
	blackList.Add('LItemLockPick100');
	blackList.Add('LItemLootIMineralsProcessed');
	blackList.Add('LItemMaceForOrcs');
	blackList.Add('LItemMiscVendorGems100');
	blackList.Add('LItemMiscVendorSoulGemEmpty');
	blackList.Add('LItemMiscVendorSoulGemFull');
	blackList.Add('LItemMS09');
	blackList.Add('LItemNecromancerRobes');
	blackList.Add('LItemOrcStronghold');
	blackList.Add('LItemOre');
	blackList.Add('LItemPenitusWeapon1H');
	blackList.Add('LItemPoison');
	blackList.Add('LItemPotion');
	blackList.Add('LItemReligiousSymbols');
	blackList.Add('LItemRobes');
	blackList.Add('LItemScroll');
	blackList.Add('LItemSilverHandWeapon');
	blackList.Add('LItemSoldierImperial');
	blackList.Add('LItemSoldierSons');
	blackList.Add('LItemSoulGemEmpty');
	blackList.Add('LItemSoulGemFull');
	blackList.Add('LItemSpellTomes');
	blackList.Add('LitemSpellTomes');
	blackList.Add('LItemSpellTOmes');
	blackList.Add('LItemStaffAlteration');
	blackList.Add('LItemStaffConjuration');
	blackList.Add('LItemStaffDestruction00');
	blackList.Add('LItemStaffDestruction25');
	blackList.Add('LItemStaffDestruction50');
	blackList.Add('LItemStaffDestruction75');
	blackList.Add('LItemStaffIllusion');
	blackList.Add('LItemStaffRestoration');
	blackList.Add('LItemSummersetShadowsArmor');
	blackList.Add('LItemTGAmuletofArticulation');
	blackList.Add('LItemThalmorDagger');
	blackList.Add('LItemThalmorShield');
	blackList.Add('LItemVampire');
	blackList.Add('LItemVigilant');
	blackList.Add('LItemWarlock');
	blackList.Add('LITemWarlockRobes');
	blackList.Add('LItemWeaponBattleAxe');
	blackList.Add('LItemWeaponBow');
	blackList.Add('LItemWeaponDagger');
	blackList.Add('LItemWeaponDwarven');
	blackList.Add('LItemWeaponGreatSword');
	blackList.Add('LItemWeaponMace');
	blackList.Add('LItemWeaponNightingale');
	blackList.Add('LItemWeaponSailor');
	blackList.Add('LItemWeaponSword');
	blackList.Add('LItemWeaponWarAxe');
	blackList.Add('LItemWeaponWarhammer');
	blackList.Add('LItemWEBattlemage');
	blackList.Add('LItemWerewolf');
	blackList.Add('LItemwerewolfBossWarhammer');
	blackList.Add('LItemWESpellsword');
	blackList.Add('LItemWEThief');
	blackList.Add('LootBanditArmor100');
	blackList.Add('LootDwarvenCenturionSoulGem');
	blackList.Add('LootFalmerOre100');
	blackList.Add('LootGoldChangeUrns');
	blackList.Add('LootSabrecatBodyParts');
	blackList.Add('LootStaffsNecromancy100');
	blackList.Add('MG04RewardLVL');
	blackList.Add('MGR01ItemList');
	blackList.Add('MGR2');
	blackList.Add('MGRitual');
	blackList.Add('MQ203AkaviriKatana');
	blackList.Add('MQ304TsunBattleAxe');
	blackList.Add('OutfitList');
	blackList.Add('PenitusGear');
	blackList.Add('PrisonerPants50');
	blackList.Add('SublistArmor');
	blackList.Add('SublistEnch');
	blackList.Add('SublistENchDaedricWarAxeAbsorb');
	blackList.Add('SublistScaledCuirassVariants');
	blackList.Add('SublistSoulGem');
	blackList.Add('SublistThalmor');
	blackList.Add('SublistWeapon');
	blackList.Add('TG02MercLItem');
	blackList.Add('TG07Chillrend');
	blackList.Add('TGLvlItemNightingale');
	blackList.Add('TGPotionof');
	blackList.Add('TGRewardPotion');
	blackList.Add('TGTQ04DeathItem');
	blackList.Add('UDGPDLC1SublistEnchVampireRobesMagickaRate');
	blackList.Add('USKPVigilantsWeaponMace');
	blackList.Add('USLEEPStormfang');
	blackList.Add('USLEEPSublistEnchDaedricBattle');
	blackList.Add('VendorEorlundSkyforgeSteelSet');
	blackList.Add('WE17BanditOutfitList');
	
	
	
	//--------------------------------
	//Blacklist NPC EditorIDs
	//--------------------------------
	
	blackList.Add('CWBattleTullius');
	blackList.Add('CWFieldCOSons');
	blackList.Add('CWSiege');
	blackList.Add('DBTreasCorpseSkeleton');
	blackList.Add('dunBleakFallsCorpseBretonThomas');
	blackList.Add('dunHonningbrewRatGuy');
	blackList.Add('dunMarkarthWizard_Guard');
	blackList.Add('DLC2dunFahlbtharzExplorerCorpse');
	blackList.Add('DLC2dunGyldenhulAdventurer');
	blackList.Add('DLC2EncHunterNordM');
	blackList.Add('DLC2KagrumezBanditBoss');
	blackList.Add('DLC2MerilarRendas');
	blackList.Add('DLC2PillarRRGuard');
	blackList.Add('DLC2ServosRendas');
	blackList.Add('DLC2WE05Wizard');
	blackList.Add('e3DemoArvel');
	blackList.Add('EncForsworn');
	blackList.Add('EncHunter');
	blackList.Add('EncVigilantOfStendarr');
	blackList.Add('GaiusMaro');
	blackList.Add('Golldir');
	blackList.Add('Jdatharr');
	blackList.Add('MQ206Gormlaith');
	blackList.Add('MQ304Froki');
	blackList.Add('Player');
	blackList.Add('SummonGormlaith');
	blackList.Add('TG08BTreasCorpseThiefNordMaleOld');
	blackList.Add('TG09TreasCorpseAnders');
	blackList.Add('TreasCorpseVigilantOfStendarrMale');
	blackList.Add('Urwa');
	blackList.Add('WEAdventurerBrawler');
	
	
	
	
	
	//--------------------------------
	//Blacklist REFR EditorIDs
	//--------------------------------
	
	blackList.Add('DefaultBookShelfBookMarker');
	blackList.Add('AleWhiterunQuest');
	blackList.Add('ArmorBoneCrown');
	blackList.Add('ArmorDragonPriestMaskWoodHelmet');
	blackList.Add('BasketCarry');
	blackList.Add('BYOHHouseGuide');
	blackList.Add('C04HagravenHead');
	blackList.Add('CasSecEntranceCrest');
	blackList.Add('CivilWarMapFlag01');
	blackList.Add('CR12TotemsOfHircine');
	blackList.Add('CWArrow');
	blackList.Add('CWDummy');
	blackList.Add('CWFort');
	blackList.Add('DA01');
	blackList.Add('DA03RuefulAxe');
	blackList.Add('DA04');
	blackList.Add('DA06Volendrung');
	blackList.Add('DA07');
	blackList.Add('DA08EbonyBlade');
	blackList.Add('DA13Afflicted');
	blackList.Add('DA14SamNote');
	blackList.Add('DA14SanguineRose');
	blackList.Add('DA14Water');
	blackList.Add('DA16SkullofCorruption');
	blackList.Add('DA16Torpor');
	blackList.Add('DancersFlute');
	blackList.Add('DB003TovaLetter');
	blackList.Add('DB01AventusLetter');
	blackList.Add('DB05ElvenBow');
	blackList.Add('DB06Schedule');
	blackList.Add('DB07Journal');
	blackList.Add('DBArmorGlovesReward');
	blackList.Add('DBBladeOfWoeReward');
	blackList.Add('DBCiceroJournal');
	blackList.Add('DLC01DrawKnife');
	blackList.Add('DLC01DweSchematics');
	blackList.Add('DLC1ElderScrollBack');
	blackList.Add('DLC01SoulCairnReaperFragment');
	blackList.Add('DLC01TortureTool01');
	blackList.Add('DLC1BoneHawk');
	blackList.Add('DLC1Book3Valuable');
	blackList.Add('DLC1DarkfallPassageNote');
	blackList.Add('DLC1DawnguardRune');
	blackList.Add('DLC1dunRedwaterDenJournal');
	blackList.Add('DLC1FVBook02English');
	blackList.Add('DLC1IvoryCrown');
	blackList.Add('DLC1LD_Aetheri');
	blackList.Add('DLC1LD_Katria');
	blackList.Add('DLC1nVampireNightPowerNecklaceBats');
	blackList.Add('DLC1RecipeFrenzy1');
	blackList.Add('DLC1RuunvaldJournal');
	blackList.Add('DLC1SoulCairnRJPOI2Note');
	blackList.Add('DLC1SpellTomeConjure');
	blackList.Add('DLC1VQ07InitiatesEwer');
	blackList.Add('DLC1V');
	blackList.Add('DLC2Bl');
	blackList.Add('DLC2dunBloodskalNote01');
	blackList.Add('DLC2dunFahlbtharzDwarvenHelmet');
	blackList.Add('DLC2dunHaknirScimitar01');
	blackList.Add('DLC2dunKarstaagSkullItemNoName');
	blackList.Add('DLC2dunKolbjornBoots');
	blackList.Add('DLC2dunKolbjornGauntlets');
	blackList.Add('DLC2dunKolbjornHelm');
	blackList.Add('DLC2dunKolbjornMinersNote');
	blackList.Add('DLC2dunKolbjornSkull');
	blackList.Add('DLC2dunKolbjornRalisJournal');
	blackList.Add('DLC2dunKolbjornRing');
	blackList.Add('DLC2dunNchardakCube');
	blackList.Add('DLC2DweKagrumezControlGemInv01');
	blackList.Add('DLC2ExpSpiderExperimentJournal');
	blackList.Add('DLC2FrostmothLetter04');
	blackList.Add('DLC2Hork');
	blackList.Add('DLC2Hrodulf');
	blackList.Add('DLC2IldariJournal');
	blackList.Add('DLC2KagrumezFateBow01');
	blackList.Add('dlc2MerchNote');
	blackList.Add('DLC2POIUshaNote01');
	blackList.Add('DLC2RR');
	blackList.Add('DLC2TG');
	blackList.Add('DLC2TT2HeartStone');
	blackList.Add('dunAbandonedPrisonNote');
	blackList.Add('dunAlftandDwemerStudy01');
	blackList.Add('dunAlftandEndrastsJournal01');
	blackList.Add('dunAlftandJ');
	blackList.Add('dunAlftandManifestJournal01');
	blackList.Add('dunAn');
	blackList.Add('dunBloatedMan');
	blackList.Add('dunBrokenOarHargarJournal');
	blackList.Add('dunC');
	blackList.Add('dunD');
	blackList.Add('dunEmbershardTatteredJournal');
	blackList.Add('dunF');
	blackList.Add('dunG');
	blackList.Add('dunHa');
	blackList.Add('dunHuntersBow');
	blackList.Add('dunIlinaltasDeepAdventurerJournal');
	blackList.Add('dunIronbindLetter');
	blackList.Add('dunK');
	blackList.Add('dunLabyrinthian');
	blackList.Add('DunLabyrinthianSpellTomeEquilibrium');
	blackList.Add('dunLiarsRetreatLonghammer');
	blackList.Add('dunLost');
	blackList.Add('dunMarkarthWizard_LabJournal');
	blackList.Add('dunMarkarthWizardSpiderControlStaff');
	blackList.Add('dunMidden');
	blackList.Add('dunMistwatch');
	blackList.Add('dunMovarthsBoots');
	blackList.Add('dunMzinchaleft');
	blackList.Add('dunN');
	blackList.Add('dunOrotheimJournal');
	blackList.Add('dunP');
	blackList.Add('DunP');
	blackList.Add('DUNPOIDragonAttackNote');
	blackList.Add('dunR');
	blackList.Add('dunSaarthalStaffJyrikStaff');
	blackList.Add('dunSerpentsBluffNote');
	blackList.Add('dunShipwreck04TriusNote');
	blackList.Add('dunSilentMoonsLunarBook');
	blackList.Add('dunSteamcragCampNote');
	blackList.Add('dunT');
	blackList.Add('dunU');
	blackList.Add('dunV');
	blackList.Add('dunW');
	blackList.Add('dunYng');
	blackList.Add('DunYngolBarrowSteelPlateHelmet');
	blackList.Add('EnchArmorDraugrHelmetResistFire03');
	blackList.Add('EnchCircletWaterbreathing');
	blackList.Add('EnchDraugrGreatswordHonedFire03');
	blackList.Add('EnchSteelBattleaxeFierySouls');
	blackList.Add('Favor');
	blackList.Add('FF');
	blackList.Add('FirebrandWine');
	blackList.Add('Freeform');
	blackList.Add('FXdustDropMedWEP');
	blackList.Add('highGateRuinsScroll');
	blackList.Add('ImperialWarHorn');
	blackList.Add('IronSwordBrokenHandle');
	blackList.Add('IronWarAxeBroken');
	blackList.Add('Letter');
	blackList.Add('Markarth');
	blackList.Add('MG03Book');
	blackList.Add('MGRArniel04SoulGem');
	blackList.Add('MGRDestruction');
	blackList.Add('MGRitual02Book');
	blackList.Add('MGRKeening');
	blackList.Add('MQ103FarengarBook');
	blackList.Add('MQ105Note');
	blackList.Add('MQ106DragonParchment');
	blackList.Add('MQPaarthurnaxBook');
	blackList.Add('MS');
	blackList.Add('NN01SinderionsJournal');
	blackList.Add('POI');
	blackList.Add('sc_ArvakSkullUNIQUE');
	blackList.Add('SolitudeToryggWarHorn');
	blackList.Add('SpellTomeTransmuteOreMineral');
	blackList.Add('SovRoastOx');
	blackList.Add('SteelBattleAxeBroken');
	blackList.Add('T0');
	blackList.Add('TG00MadesiRing');
	blackList.Add('TG01HaelgaStatue');
	blackList.Add('TG02BillofSale');
	blackList.Add('TG03SabjornLetter');
	blackList.Add('TG04');
	blackList.Add('TG05GallusJournalPre');
	blackList.Add('TG07Chillrend001');
	blackList.Add('TG07MercersPlans');
	blackList.Add('TG08SkeletonKey');
	blackList.Add('TGBook0NightingalesVolume');
	blackList.Add('TGCrown');
	blackList.Add('TGFenceCaravanSatchel');
	blackList.Add('TGLT');
	blackList.Add('TGTQ');
	blackList.Add('TGRFOValueItem');
	blackList.Add('TGRGeneralValueItem');
	blackList.Add('TGTQ03SolitudeLetter');
	blackList.Add('TrapDweBallistaBoltAmmo01');
	blackList.Add('Windhelm');
	blackList.Add('YsgramorsBladePiece07');
	
	
	lastPercent := 0;

	for i := 0 to MaxPatchRecordIndex do begin
		rec := GetPatchRecord(i);

		//--------------------------------
		//Current process message
		//--------------------------------
		currentFile := BaseName(GetFile(Master(rec)));
		if not (Signature(rec) = currentSignature) then begin
				currentSignature := Signature(rec);
				AddMessage('----------------------------------------------------------------');
				AddMessage('Now patching ' + currentSignature + ' in ' + currentFile);
				AddMessage('----------------------------------------------------------------');
		end;

		//--------------------------------
		//Percent done message
		//--------------------------------
		if not (MaxPatchRecordIndex = 0) then begin
			if ((i  * 100) div MaxPatchRecordIndex) > lastPercent then begin
				AddMessage(IntToStr((i  * 100) div MaxPatchRecordIndex) + '% patched!');
				lastPercent := lastPercent + 1;
			end;
		end;
		
		editorID := geev(rec, 'EDID');
		formID := HexFormID(rec);

		//--------------------------------
		//Process records
		//--------------------------------
		if currentSignature = 'REFR' then begin
			
			//Assign utility variables
			rName := geev(rec, 'NAME');
			rSignature := getSignature(rName);
			rEditorID := getEditorID(rName);
			rFormID := getFormID(rName);
			
			//Check for potential errors and sort out records that shall not be processed
			if (not Assigned(ebip(rec, 'NAME'))) or (not hasPovertySignature(rSignature)) or (Copy(rEditorID, 0, 5) = 'Dummy') or IsInTStringListCopy(blackList, rEditorID) then begin
				Remove(rec);
				Continue;
			end
			else begin
				rItemRecord := RecordByHexFormID(rFormID);
				
				//Add poverty LVLI record
				lvliRecord := AddLVLI(mxPatchFile, rItemRecord, 'REFR', rEditorID, rFormID);
				
				//Add XLIB to reference
				if not Assigned(ebip(rec, 'XLIB')) then
					Add(rec, 'XLIB', true);
				seev(rec, 'XLIB', HexFormID(lvliRecord));
				
				//Check for keywords of the placed base record
				
				
				if IsWinningOverride(rItemRecord) then begin
					for j := 0 to ElementCount(ebip(rItemRecord, 'KWDA')) - 1 do begin
						referenceKeywords.Add(getEditorID(geev(rItemRecord, 'KWDA\[' + IntToStr(j) + ']')));
					end;
				end
				else begin
					for j := 0 to ElementCount(ebip(WinningOverride(rItemRecord), 'KWDA')) - 1 do begin
						referenceKeywords.Add(getEditorID(geev(WinningOverride(rItemRecord), 'KWDA\[' + IntToStr(j) + ']')));
					end;
				end;				
				
				//Change the name
				Case Pos(rSignature, 'ALCH|AMMO|ARMO|BOOK|INGR|MISC|SLGM|WEAP') of
					1: 	begin
							seev(rec, 'NAME', dummyFood);
							if getEditorID(geev(rItemRecord, 'ENIT\Sound - Consume')) = 'ITMPotionUse' then
								seev(rec, 'NAME', dummyDrink);
							for j := 0 to referenceKeywords.Count - 1 do begin
								Case Pos(referenceKeywords[j], 'VendorItemPotion|VendorItemPoison') of
									1: seev(rec, 'NAME', dummyPotion);
									18: seev(rec, 'NAME', dummyPotion);
								end;
							end;
						end;
					6: seev(rec, 'NAME', dummyArrow);
					11: begin
							for j := 0 to referenceKeywords.Count - 1 do begin
								Case Pos(referenceKeywords[j], 'ArmorBoots|ArmorCuirass|ArmorGauntlets|ArmorHelmet|ArmorShield|ClothingCirclet|ClothingRing|ClothingNecklace|ClothingFeet|ClothingBody|ClothingHands|ClothingHead') of
									1:	begin 
											seev(rec, 'NAME', dummyBoots);
											Break;
										end;
									12: begin 
											seev(rec, 'NAME', dummyCuirass);
											Break;
										end;
									25: begin 
											seev(rec, 'NAME', dummyGauntlets);
											Break;
										end;
									40: begin 
											seev(rec, 'NAME', dummyHelmet);
											Break;
										end;
									52: begin 
											seev(rec, 'NAME', dummyShield);
											Break;
										end;
									64: begin 
											seev(rec, 'NAME', dummyCirclet);
											Break;
										end;
									80: begin 
											seev(rec, 'NAME', dummyRing);
											Break;
										end;
									93: begin 
											seev(rec, 'NAME', dummyAmulet);
											Break;
										end;
									110: begin 
											seev(rec, 'NAME', dummyBoots);
											Break;
										end;
									123: begin 
											seev(rec, 'NAME', dummyCuirass);
											Break;
										end;
									136: begin 
											seev(rec, 'NAME', dummyGauntlets);
											Break;
										end;
									150: begin 
											seev(rec, 'NAME', dummyHelmet);
											Break;
										end;
								end;
							end;
						end;
					16: seev(rec, 'NAME', dummyBook);
					21: seev(rec, 'NAME', dummyIngredient);
					26: begin
							seev(rec, 'NAME', dummyClutter);
							if rEditorID = 'Gold001' then begin
								seev(rec, 'NAME', dummySeptim);
								Continue;
							end;
							for j := 0 to ReferencedByCount(rItemRecord) - 1 do begin
								if getSignature(geev(ReferencedByIndex(rItemRecord, j), 'Record Header\FormID')) = 'COBJ' then begin
									seev(rec, 'NAME', dummyResource);
									Break;
								end;
							end;
						end;
					31: seev(rec, 'NAME', dummySoulGem);
					36: begin
							for j := 0 to referenceKeywords.Count - 1 do begin
								Case Pos(referenceKeywords[j], 'WeapTypeBattleaxe|WeapTypeBow|WeapTypeDagger|WeapTypeGreatsword|WeapTypeMace|WeapTypeSword|WeapTypeWarAxe|WeapTypeWarhammer|WeapTypeStaff') of
									1: 	begin 
											seev(rec, 'NAME', dummyBattleaxe);
											Break;
										end;
									19: begin 
											seev(rec, 'NAME', dummyBow);
											Break;
										end;
									31: begin 
											seev(rec, 'NAME', dummyDagger);
											Break;
										end;
									46: begin 
											seev(rec, 'NAME', dummyGreatSword);
											Break;
										end;
									65: begin 
											seev(rec, 'NAME', dummyMace);
											Break;
										end;
									78: begin 
											seev(rec, 'NAME', dummySword);
											Break;
										end;
									92: begin 
											seev(rec, 'NAME', dummyWarAxe);
											Break;
										end;
									107:begin 
											seev(rec, 'NAME', dummyWarhammer);
											Break;
										end;
									125:begin 
											seev(rec, 'NAME', dummyStaff);
											Break;
										end;
								end;
							end;
						end;
					else begin
						failedFormIDs.Add(geev(rec, 'Record Header\FormID'));
						Remove(rec);
						Continue;
					end;
				end;
				
				//Remove record if it was not successfully processed
				if not (Copy(getEditorID(geev(rec, 'NAME')), 0, 5) = 'Dummy') then begin
					failedFormIDs.Add(geev(rec, 'Record Header\FormID'));
					Remove(rec);
					Continue;
				end;
				
				//Clear TStringLists
				referenceKeywords.Clear;
			end;
		end
		else if currentSignature = 'CONT' then begin
			if (not Assigned(ebip(rec, 'Items'))) or IsInTStringListCopy(blackList, EditorID(rec)) then begin
				Remove(rec);
				Continue;
			end
			else begin
				//Add items to list and delete them
				k := 0;
				for j := 0 to ElementCount(ebip(rec, 'Items')) - 1 do begin
					item := geev(rec, 'Items\[' + IntToStr(k) + ']\CNTO\Item');
					if (getSignature(item) = 'LVLI') or (getSignature(item) = 'KEYM') or (Copy(getEditorID(item), 0, 5) = 'Dummy') or IsInTStringListCopy(blackList, getEditorID(item)) then begin
						k := k + 1;
					end
					else begin
						cItem := ebip(rec, 'Items\[' + IntToStr(k) + ']');
						cItemsList.Add(geev(rec, 'Items\[' + IntToStr(k) + ']\CNTO\Item'));
						cCountsList.Add(geev(rec, 'Items\[' + IntToStr(k) + ']\CNTO\Count'));
						Remove(cItem);
						
					end;
				end;
				if cItemsList.Count = 0 then begin
					Remove(rec);
					Continue;
				end;
				//Create new items and their Leveled List
				for j := 0 to cItemsList.Count - 1 do begin
					cNewItem := cItemsList[j];
					if ContainsText(cNewItem, 'Error: Could not be resolved') then begin
						errorFormIDs.Add(cNewItem + ' in ' + editorID ' in file ' + currentFile);
						Continue;
					end;
					cEditorID := getEditorID(cNewItem);
					//Add poverty LVLI record
					lvliRecord := AddLVLI(mxPatchFile, rec, 'CONT', cEditorID, getFormID(cNewItem));
					//Add new item and change its values
					cItem := ElementAssign(ebip(rec, 'Items'), HighInteger, nil, false);
					seev(cItem, 'CNTO\Item', geev(lvliRecord, 'Record Header\FormID'));
					seev(cItem, 'CNTO\Count', cCountsList[j]);
				end;
			end;
			cItemsList.Clear;
			cCountsList.Clear;
		end
		else if currentSignature = 'FLOR' then begin
			if (not Assigned(ebip(rec, 'PFIG'))) or IsInTStringListCopy(blackList, EditorID(rec)) then begin
				Remove(rec);
				Continue;
			end
			else begin
				//Assign utility variables
				fIngredient := geev(rec, 'PFIG');
				fSignature := getSignature(fIngredient);
				fEditor := getEditorID(fIngredient);
				fFormID := getFormID(fIngredient);
				
				//Sort out records that shall not be processed
				if (not (fSignature = 'ALCH')) and (not (fSignature = 'INGR')) then begin
					Remove(rec);
					Continue;
				end;
				
				//Add poverty LVLI record
				lvliRecord := AddLVLI(mxPatchFile, rec, 'FLOR', fEditor, fFormID);
				
				//Change PFIG value
				seev(rec, 'PFIG', geev(lvliRecord, 'Record Header\FormID'));
			end;
		end
		else if currentSignature = 'LVLI' then begin
			lEntries := ebip(rec, 'Leveled List Entries');
			if (not Assigned(lEntries)) or IsInTStringListCopy(blackList, EditorID(rec)) then begin
				Remove(rec);
				Continue;
			end
			else begin
				//Add items to list and delete them
				k := 0;
				for j := 0 to ElementCount(lEntries) - 1 do begin
					if (getSignature(geev(rec, 'Leveled List Entries\[' + IntToStr(k) + ']\LVLO\Reference')) = 'KEYM') or (getSignature(geev(rec, 'Leveled List Entries\[' + IntToStr(k) + ']\LVLO\Reference')) = 'LVLI') or IsInTStringListCopy(blackList, getEditorID(item)) or (Copy(getEditorID(geev(rec, 'Leveled List Entries\[' + IntToStr(k) + ']\LVLO\Reference')), 0, 5) = 'Dummy') then begin
						k := k + 1;
					end
					else begin
						lEntry := ebip(rec, 'Leveled List Entries\[' + IntToStr(k) + ']');
						lLevelList.Add(geev(rec, 'Leveled List Entries\[' + IntToStr(k) + ']\LVLO\Level'));
						lReferenceList.Add(geev(rec, 'Leveled List Entries\[' + IntToStr(k) + ']\LVLO\Reference'));
						lCountList.Add(geev(rec, 'Leveled List Entries\[' + IntToStr(k) + ']\LVLO\Count'));
						Remove(lEntry);
					end;
				end;
				
				if lLevelList.Count = 0 then begin
					Remove(rec);
					Continue;
				end;
				
				//Create new items and their Leveled List
				for j := 0 to lReferenceList.Count - 1 do begin
					lNewItem := lReferenceList[j];
					
					//Check for errors
					if ContainsText(lNewItem, 'Error: Could not be resolved') then begin
						errorFormIDs.Add(lNewItem + ' in ' + editorID);
						Continue;
					end;
					
					//Assign utility variables
					lEditorID := getEditorID(lNewItem);
					lSignature := getSignature(lNewItem);
					
					//Add poverty LVLI record
					lvliRecord := AddLVLI(mxPatchFile, rec, 'LVLI', lEditorID, getFormID(lNewItem));
					
					//Add new entry and change its values
					lEntry := ElementAssign(lEntries, HighInteger, nil, false);
					seev(lEntry, 'LVLO\Level', lLevelList[j]);
					seev(lEntry, 'LVLO\Reference', geev(lvliRecord, 'Record Header\FormID'));
					seev(lEntry, 'LVLO\Count', lCountList[j]);
				end;
			end;
			lLevelList.Clear;
			lReferenceList.Clear;
			lCountList.Clear;
		end
		else if currentSignature = 'NPC_' then begin
			if (not Assigned(ebip(rec, 'Items'))) or IsInTStringListCopy(blackList, EditorID(rec)) then begin
				Remove(rec);
				Continue;
			end
			else begin
				//Add items to list and delete them
				k := 0;
				for j := 0 to ElementCount(ebip(rec, 'Items')) - 1 do begin
					item := geev(rec, 'Items\[' + IntToStr(k) + ']\CNTO\Item');
					nSignature := getSignature(item);
					if (nSignature = 'LVLI') or (nSignature = 'KEYM') or (nSignature = 'WEAP') or (nSignature = 'ARMO') or (nSignature = 'AMMO') or (geev(rec, 'Items\[' + IntToStr(k) + ']\CNTO\Count') = 1) or (Copy(getEditorID(item), 0, 5) = 'Dummy') or IsInTStringListCopy(blackList, getEditorID(item)) then begin
						k := k + 1;
					end
					else begin
						cItem := ebip(rec, 'Items\[' + IntToStr(k) + ']');
						cItemsList.Add(geev(rec, 'Items\[' + IntToStr(k) + ']\CNTO\Item'));
						cCountsList.Add(geev(rec, 'Items\[' + IntToStr(k) + ']\CNTO\Count'));
						Remove(cItem);
					end;
				end;
				
				if cItemsList.Count = 0 then begin
					Remove(rec);
					Continue;
				end;
				
				for j := 0 to cItemsList.Count - 1 do begin
					cNewItem := cItemsList[j];
					
					//Check for errors
					if ContainsText(cNewItem, 'Error: Could not be resolved') then begin
						errorFormIDs.Add(cNewItem + ' in ' + editorID);
						Continue;
					end;
					
					//Assign utility variables
					cEditorID := getEditorID(cNewItem);
					nSignature := getSignature(cNewItem);
					
					//Add poverty LVLI record
					lvliRecord := AddLVLI(mxPatchFile, rec, 'NPC_', cEditorID, getFormID(cNewItem));
					
					//Add new item and change its values
					cItem := ElementAssign(ebip(rec, 'Items'), HighInteger, nil, false);
					seev(cItem, 'CNTO\Item', geev(lvliRecord, 'Record Header\FormID'));
					seev(cItem, 'CNTO\Count', cCountsList[j]);
				end;
			end;
			cItemsList.Clear;
			cCountsList.Clear;
		end
		else if currentSignature = 'TREE' then begin
			if (not Assigned(ebip(rec, 'PFIG'))) or IsInTStringListCopy(blackList, EditorID(rec)) then begin
				Remove(rec);
				Continue;
			end
			else begin
				tIngredient := geev(rec, 'PFIG');
				tEditorID := getEditorID(tIngredient);
				tSignature := getSignature(tIngredient);
				tFormID := getFormID(tIngredient);
				if (not (tSignature = 'ALCH')) and (not (tSignature = 'INGR')) then begin
					Remove(rec);
					Continue;
				end;
				
				//Add poverty LVLI record
				lvliRecord := AddLVLI(mxPatchFile, rec, 'TREE', tEditorID, tFormID);
				
				//Change PFIG value
				seev(rec, 'PFIG', geev(lvliRecord, 'Record Header\FormID'));
			end;
		end;
	end;

	//--------------------------------
	//Final warnings
	//--------------------------------
	if failedFormIDs.Count > 0 then begin
		AddMessage(' ');
		AddMessage('WARNING: Those References were not patched due to a lack of keywords in their base record');
		AddMessage(' ');
		AddMessageTStringList(failedFormIDs);
    end;
	if errorFormIDs.Count > 0 then begin
		AddMessage(' ');
		AddMessage('WARNING: Those records could not be used as they contain an error | Please contact the mod author politely');
		AddMessage(' ');
		AddMessageTStringList(errorFormIDs);
    end;

	//--------------------------------
	//MXPF Finalization
	//--------------------------------
	FinalizeMXPF;
end;

//--------------------------------
//Utility functions
//--------------------------------

function getFormID(s: string): string;
begin
  Result := Copy(s, Pos('[', s) + 6, 8);
end;

function getEditorID(s: string): string;
begin
  Result := Copy(s, 0, Pos(' ', s) - 1);
end;

function getSignature(s: string): string;
begin
  Result := Copy(s, Pos('[', s) + 1, 4);
end;

function RecordByEditorIDAllFiles(group, eid: string): IInterface;
var
    i: integer;
begin
    Result := nil;
    for i := 0 to FileCount - 1 do begin
				if HasGroup(FileByIndex(i), group) then begin
          if Assigned(MainRecordByEditorID(GroupBySignature(FileByIndex(i), group), eid)) then begin
						Result := MainRecordByEditorID(GroupBySignature(FileByIndex(i), group), eid);
            Exit;
          end
				end
    end
end;

function IsInTStringList(sl: TStringList; s: string): boolean;
var
	i: integer;
begin
	Result := false;
	for i := 0 to sl.Count - 1 do begin
		if sl.IndexOf(s) > -1  then begin
			Result := true;
			Exit;
		end;
	end;
end;

function IsInTStringListCopy(sl: TStringList; s: string): boolean;
var
	i: integer;
begin
	Result := false;
	for i := 0 to sl.Count - 1 do begin
		if Copy(s, 0, Length(sl[i])) = sl[i] then begin
			Result := true;
			Exit;
		end;
	end;
end;

procedure AddMessageTStringList(sl: TStringList);
var
	i: integer;
begin
	for i := 0 to sl.Count - 1 do begin
		AddMessage(sl[i]);
	end;
end;

procedure AddMessageCurrentItemsStructure(rec: IInterface);
var
	i: integer;
begin
	for i := 0 to ElementCount(ebip(rec, 'Items')) - 1 do begin
		AddMessage(IntToStr(i) + ': ' + geev(rec, 'Items\[' + IntToStr(i) + ']\CNTO\Item'));
	end;
end;

function hasPovertySignature(s: string): bool;
var
	i: integer;
begin
	Result := false;
	if ContainsText('ALCH|AMMO|ARMO|BOOK|INGR|MISC|SLGM|WEAP', s) then
		Result := true;
end;

function AddLVLI(f, rec: IInterface; origin, eid, fid: string): IInterface;
var
	i: integer;
	referenceKeywords: TStringList;
	signature, reference, povertyFileLoadOrder, pAmmo, pArmor, pBook, pIngredient, pClutter, pSoulGem, pWeapon, pFood, pHarvestFoodFlora, pPotion, pResource, pGold, pDrink, pHarvestIngredientsFlora, pHarvestFoodNPC, pHarvestResourceNPC, pAmmoNPC, pMerchantGold, pBookSpell, pHarvestFoodFloraHanging, pHarvestIngredientsNPC, pMineNotInUse, pBugFishNotInUse: string;
	innerlvli, lvli, itemRecord, fidRecord: IInterface;
begin
	//Get global value from Poverty
	povertyFileLoadOrder := IntToStr(GetLoadOrder(FileByName('Poverty.esp')));
	//ALCH
	pHarvestFoodFlora := povertyFileLoadOrder + '00AA19';
	pHarvestFoodNPC := povertyFileLoadOrder + '01A023';
	pFood := povertyFileLoadOrder + '00AA18';
	pPotion := povertyFileLoadOrder + '00AA1A';
	pDrink := povertyFileLoadOrder + '014C21';
	//AMMO
	pAmmo := povertyFileLoadOrder + '000802';
	pAmmoNPC := povertyFileLoadOrder + '01A17E';
	//ARMO
	pArmor := povertyFileLoadOrder + '005911';
	//BOOK
	pBook := povertyFileLoadOrder + '005912';
	pBookSpell := povertyFileLoadOrder + '01A21F';
	//INGR
	pIngredient := povertyFileLoadOrder + '005913';
	pHarvestIngredientsNPC := povertyFileLoadOrder + '01A3DA';
	pHarvestIngredientsFlora := povertyFileLoadOrder + '014CA1';
	//MISC
	pClutter := povertyFileLoadOrder + '005914';
	pResource := povertyFileLoadOrder + '00AA1B';
	pHarvestResourceNPC := povertyFileLoadOrder + '01A162';
	pGold := povertyFileLoadOrder + '00FB1E';
	pMerchantGold := povertyFileLoadOrder + '01A17F';
	//SLGM
	pSoulGem := povertyFileLoadOrder + '005915';
	//WEAP
	pWeapon := povertyFileLoadOrder + '005916';
	//Not used right now
	pHarvestFoodFloraHanging := povertyFileLoadOrder + '01A3D7';
	pMineNotInUse := povertyFileLoadOrder + '01A44E';
	pBugFishNotInUse := povertyFileLoadOrder + '01A44F';
	
	referenceKeywords := TStringList.Create;
	
	//If reference is LVLI get the first non LVLI entry
	fidRecord := RecordByHexFormID(fid);
	if not IsWinningOverride(fidRecord) then
		fidRecord := WinningOverride(fidRecord);
	signature := getSignature(BaseName(fidRecord));
	
	if signature = 'LVLI' then begin
		innerlvli := RecordByHexFormID(getFormID(geev(fidRecord, 'Leveled List Entries\[0]\LVLO\Reference')));
		while Assigned(innerlvli) and (signature = 'LVLI') do begin
			signature := getSignature(BaseName(innerlvli));
			if signature = 'LVLI' then begin
				if Assigned(RecordByHexFormID(getFormID(geev(innerlvli, 'Leveled List Entries\[0]\LVLO\Reference')))) then begin
					innerlvli := WinningOverride(RecordByHexFormID(getFormID(geev(innerlvli, 'Leveled List Entries\[0]\LVLO\Reference'))));
					if not IsWinningOverride(innerlvli) then
						innerlvli := WinningOverride(innerlvli);
				end
				else begin
					signature := getSignature(BaseName(fidRecord));
				end;
			end;
		end;
	end
	else begin
		innerlvli := fidRecord;
	end;
	
	//Special cases
	if ContainsText(geev(fidRecord, 'EDID'), 'Gold') and ContainsText(geev(fidRecord, 'EDID'), 'Vendor') then begin
		eid := eid + '_MERCHANT';
	end
	else if ContainsText(geev(fidRecord, 'EDID'), 'SpellTome') or ContainsText(geev(fidRecord, 'EDID'), 'Scroll') then begin
		eid := eid + '_SPELL';
	end
	else if origin = 'NPC_' then begin
		for i := 0 to ReferencedByCount(fidRecord) - 1 do begin
			if getSignature(geev(ReferencedByIndex(fidRecord, i), 'Record Header\FormID')) = 'COBJ' then begin
				eid := eid + '_NPC';
				Break;
			end;
		end;
		if signature = 'AMMO' then
			eid := eid + '_NPC';
	end;
	
	//Add LVLI record
	lvli := RecordByEditorIDAllFiles('LVLI', 'p' + eid);
	if not Assigned(lvli) then begin
		
		//Add group record and lvliRecord
		if not Assigned(GroupBySignature(f, 'LVLI')) then
			Add(f, 'LVLI', true);
		lvli := Add(GroupBySignature(f, 'LVLI'), 'LVLI', true);
		Result := lvli;
		//Add EditorID
		Add(lvli, 'EDID', true);
		seev(lvli, 'EDID', 'p' + eid);
		
		//Add Flag
		SetNativeValue(ebip(lvli, 'LVLF'), GetNativeValue(ebip(lvli, 'LVLF')) or 1 shl 1);
		
		//Add Count
		Add(lvli, 'LLCT', true);
		seev(lvli, 'LLCT', '1');
		
		//Add Leveled List Entry
		Add(lvli, 'Leveled List Entries', true);
		seev(lvli, 'Leveled List Entries\[0]\LVLO\Level', '1');
		seev(lvli, 'Leveled List Entries\[0]\LVLO\Reference', fid);
		seev(lvli, 'Leveled List Entries\[0]\LVLO\Count', '1');
		//Add Global
		Add(lvli, 'LVLG', true);
		if IsWinningOverride(fidRecord) then begin
			for i := 0 to ElementCount(ebip(fidRecord, 'KWDA')) - 1 do begin
				referenceKeywords.Add(getEditorID(geev(fidRecord, 'KWDA\[' + IntToStr(i) + ']')));
			end;
		end
		else begin
			for i := 0 to ElementCount(ebip(WinningOverride(fidRecord), 'KWDA')) - 1 do begin
				referenceKeywords.Add(getEditorID(geev(WinningOverride(fidRecord), 'KWDA\[' + IntToStr(i) + ']')));
			end;
		end;
		Case Pos(signature, 'ALCH|AMMO|ARMO|BOOK|INGR|MISC|SLGM|WEAP|SCRL') of
			//Process ALCH global
			1: 	begin
					if (origin = 'FLOR') or (origin = 'TREE') then begin
						seev(lvli, 'LVLG', pHarvestFoodFlora);
					end
					else if (origin = 'NPC_') then begin
						seev(lvli, 'LVLG', pHarvestFoodNPC);
					end
					else begin
						seev(lvli, 'LVLG', pFood);
						if getEditorID(geev(fidRecord, 'ENIT\Sound - Consume')) = 'ITMPotionUse' then
							seev(lvli, 'LVLG', pDrink);
						for i := 0 to referenceKeywords.Count - 1 do begin
							Case Pos(referenceKeywords[i], 'VendorItemPotion|VendorItemPoison') of
								1: seev(lvli, 'LVLG', pPotion);
								18: seev(lvli, 'LVLG', pPotion);
							end;
						end;
					end;
				end;
			//Process AMMO global
			6: 	begin
					if Copy(eid, length(eid) - 3, 4) = '_NPC' then begin
						seev(lvli, 'LVLG', pAmmoNPC);
					end
					else begin
						seev(lvli, 'LVLG', pAmmo);
					end;
				end;
			//Process ARMO global
			11: seev(lvli, 'LVLG', pArmor);
			//Process BOOK global
			16: begin
					if Copy(eid, length(eid) - 5, 6) = '_SPELL' then begin
						seev(lvli, 'LVLG', pBookSpell);
					end
					else begin
						seev(lvli, 'LVLG', pBook);
					end;
				end;
			//Process INGR global
			21: begin
					if (origin = 'FLOR') or (origin = 'TREE') then begin
						seev(lvli, 'LVLG', pHarvestIngredientsFlora);
					end
					else if origin = 'NPC_' then begin
						seev(lvli, 'LVLG', pHarvestIngredientsNPC);
					end
					else begin
						seev(lvli, 'LVLG', pIngredient);
					end;
				end;
			//Process MISC global
			26: begin
					seev(lvli, 'LVLG', pClutter);
					if Copy(eid, length(eid) - 8, 9) = '_MERCHANT' then begin
						seev(lvli, 'LVLG', pMerchantGold);
					end
					else if ContainsText(geev(fidRecord, 'EDID'), 'Gold') then begin
						seev(lvli, 'LVLG', pGold);
					end;
					if Copy(eid, length(eid) - 3, 4) = '_NPC' then begin
						seev(lvli, 'LVLG', pHarvestResourceNPC);
					end
					else begin
						for i := 0 to ReferencedByCount(innerlvli) - 1 do begin
							if getSignature(geev(ReferencedByIndex(innerlvli, i), 'Record Header\FormID')) = 'COBJ' then begin
								seev(lvli, 'LVLG', pResource);
								Break;
							end;
						end;
					end;
				end;
			//Process SLGM global
			31: seev(lvli, 'LVLG', pSoulGem);
			//Process WEAP global
			36: seev(lvli, 'LVLG', pWeapon);
			//Process SCRL global
			41: seev(lvli, 'LVLG', pBookSpell);
		end;
	end
	else begin
		Result := lvli;
	end;
end;

end.
